[package]
name = "ezekieltem/op-railgun"
repository = "https://github.com/ezekieltem/OP-Railgun"
description = "A fork of the Railgun weapon used by Innovation Inc and Innovation Security. "
license = "MIT"
authors = ["TheNexusAvenger","ezekieltem"]
version = "1.5.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "Distribution.luau", "Packages", "Packages/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
NexusAppendage = "thenexusavenger/nexus-appendage@1.2.0"
railgun = "innovation-inc-roblox/railgun@1.5.1"